module.exports = {
  EXPENSE_CATEGORIES: [
    "food",
    "shopping",
    "bills",
    "transport",
    "entertainment",
    "healthcare",
    "utilities",
    "salary",
    "income",
    "credit_card_payment",
    "other",
  ],

  CATEGORY_KEYWORDS: {
    food: [
      "restaurant",
      "cafe",
      "food",
      "delivery",
      "zomato",
      "swiggy",
      "uber eats",
      "starbucks",
      "mcdonald",
      "tiền ăn",
      "tien an",
      "đồ ăn",
      "do an",
      "ăn uống",
      "an uong",
    ],
    shopping: [
      "amazon",
      "flipkart",
      "mall",
      "store",
      "shop",
      "retail",
      "purchase",
      "mua sắm",
      "mua sam",
    ],
    bills: [
      "bill payment",
      "electricity",
      "internet",
      "phone",
      "mobile recharge",
      "hóa đơn",
      "hoa don",
      "thanh toán",
      "thanh toan",
    ],
    transport: [
      "uber",
      "ola",
      "taxi",
      "fuel",
      "petrol",
      "gas",
      "metro",
      "transit",
      "xe",
      "đi lại",
      "di lai",
      "xăng",
      "xang",
    ],
    entertainment: [
      "movie",
      "cinema",
      "netflix",
      "spotify",
      "prime",
      "ticket",
      "giải trí",
      "giai tri",
      "vui chơi",
      "vui choi",
    ],
    healthcare: [
      "hospital",
      "pharmacy",
      "medical",
      "clinic",
      "doctor",
      "medicine",
      "bệnh viện",
      "benh vien",
      "thuốc",
      "thuoc",
      "y tế",
      "y te",
    ],
    utilities: [
      "water",
      "electricity",
      "gas",
      "internet",
      "telecom",
      "điện",
      "dien",
      "nước",
      "nuoc",
    ],
    salary: [
      "salary",
      "credited",
      "income",
      "payment received",
      "lương",
      "luong",
      "thu nhập",
      "thu nhap",
    ],
    income: [
      "nhận tiền",
      "nhan tien",
      "thu tiền",
      "thu tien",
      "income",
      "receive",
      "received",
    ],
    credit_card_payment: [
      "sao kê",
      "sao ke",
      "credit card",
      "thẻ tín dụng",
      "the tin dung",
      "thanh toán thẻ",
      "thanh toan the",
    ],
  },

  BANK_PATTERNS: {
    // Common bank email patterns
    senders: ["alerts@", "notify@", "noreply@", "notification@"],

    // Transaction keywords in subject/body
    keywords: [
      "transaction",
      "debited",
      "credited",
      "spent",
      "payment",
      "withdrawn",
      "purchase",
      "transfer",
    ],
  },

  GMAIL_SCOPES: ["https://www.googleapis.com/auth/gmail.readonly"],
};
